variables:
  VERSION_NUMBER: "0"

stages:
  - package
 
package:
  stage: package
  script:
    - $commitMessage = git describe --tags
    - $pattern = 'v\d+\.\d+\.\d+$'
    - if ($commitMessage -match $pattern) { $VERSION_NUMBER = $commitMessage } else {exit 0}
    - dotnet build OVFSliceViewer.sln
    - $VERSION_NUMBER = $VERSION_NUMBER[0].Substring(1)
    - echo $VERSION_NUMBER
    - dotnet pack OVFSliceViewer.sln -c Release  --output "$PWD\bin\" /p:DebugType=embedded /p:DebugSymbols=true /p:EmbedAllSources=true /p:Version=$VERSION_NUMBER 
    - dotnet nuget push $PWD\bin\*.nupkg --source DAP
  only:
    - master
  environment: production
  
  